Feature / Artemis ID
ringpublishing/RingPublishingTracking-iOS pull request #19
Opened 2023-11-14 13:38 UTC by jfk056

2023-11-15 07:23 UTC, adamszeremeta requested changes
We would need also:
-swiftlint fix (https://bamboo.grupa.onet/browse/MIOS-APTRACK48-2)
- changelog added (as 1.4.0)
- bumper project version to 1.4.0 (demo project)

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Networking/Endpoints/Responses/ArthemisResponse.swift
> +        let models: Models
I just wonder if this should be handled as blackbox or not - I will aks Michał for confirmation

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Networking/Endpoints/Responses/ArthemisResponse.swift
> +        let external: ArtemisObject.ID.External = .init(model: user.id.model, models: user.id.models.atsRi)
I would always write it as ArtemisObject.ID.External(model: user.id.model, models: user.id.models.atsRi)

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Tracking/Events/EventsService.swift
> +    func setup(delegate: EventsServiceDelegate?, session: NetworkSession = URLSession.shared) {
missing delegate param in method comment

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Tracking/Events/EventsService.swift
> +                        self.retryArtemisRequest(eaUUID: eaUUID) { artemisResult in
maybe we could flatten it a little by extracting to other helper methods?

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Public/Model/TrackingIdentifier.swift
> +    public struct EaUUID {
could we have those models in separate files? just public stuff, codable entities can be like you did them

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Networking/Models/Artemis.swift
> +public struct ArtemisObject: Codable {
should not be public (as it is in private directory), better to have separate public model

2023-11-15 07:23 UTC, adamszeremeta commented on Sources/RingPublishingTracking/Private/Networking/Models/Artemis.swift
> +public struct ArtemisObject: Codable {
and for public stuff, each property and object should have a comment saying that it is

2023-11-21 07:11 UTC, danielcalka commented on Sources/RingPublishingTracking/Private/Decorator/Generic/UserDataDecorator.swift
> +        guard let data = data, data.sso != nil || data.id != nil else { return nil }
Tutaj mamy chyba rozbieżność z androidem - u nas dodajemy RDLU tylko jeśli artemis != null. Tutaj możemy dodać dla samego sso. Która wersja jest ok?

2023-11-21 07:16 UTC, danielcalka approved these changes

2023-11-21 08:15 UTC, adamszeremeta approved these changes

2023-11-21 08:15 UTC, merged